pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'cd src/ && composer install'
            }
        }
        stage('Test') {
            steps {
                echo '@todo..'
            }
        }
        stage('Deploy') {
            steps {
                sh 'rm -r /var/www/test.vvadmin.dev/* || true'
                sh 'chmod -R 777 /var/lib/jenkins/workspace/vvadmin/deploy_test/src/web/assets && chmod -R 777 /var/lib/jenkins/workspace/vvadmin/deploy_test/src/runtime'
                sh 'mv /var/lib/jenkins/workspace/vvadmin/deploy_test/src/* /var/www/test.vvadmin.dev/'
            }
        }
    }
}