pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'cd src/ && composer install'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                sh 'cp ${WORKSPACE}/src/. /var/www/test.vvadmin.dev/'
            }
        }
    }
}